/**
 * Bundle loading – build-time switch between the synthetic demo bundle and the
 * real federation bundle. The real bundle lives in src/data-real/*.local.json,
 * is generated by `npm run import:artistic` and is GITIGNORED (privacy:
 * real athlete data, partly minors – docs/SECURITY.md → PRIVACY).
 * Real builds: `npm run build:real` / `npm run dev:real` (VITE_REAL=1).
 */
import type { DataBundle } from './provider';

const realModules = import.meta.glob('../data-real/*.local.json');

export async function loadBundle(): Promise<DataBundle> {
  if (import.meta.env.VITE_REAL === '1') {
    const key = Object.keys(realModules)[0];
    if (!key) throw new Error('Kein echtes Bundle gefunden – zuerst `npm run import:artistic` ausführen (src/data-real/*.local.json).');
    const m = (await realModules[key]()) as { default?: DataBundle };
    return (m.default ?? m) as DataBundle;
  }
  const m = await import('./seed/bundle.json');
  return (m.default ?? (m as unknown)) as DataBundle;
}
